# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)

# Display the first document in the results using pprint
print("First result:")
results = establishments.find(query)
pprint(results[0])

First result:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64caefb5644c716772b90bd6'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
results = establishments.find(query)
scores_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print("Number of rows in result: ", len(scores_df))
# Display the first 10 rows of the DataFrame
scores_df.head(10)

Number of rows in result:  41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64caefb5644c716772b90bd6,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64caefb5644c716772b90f4d,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64caefb5644c716772b91258,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64caefb5644c716772b9144e,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64caefb5644c716772b91455,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64caefb6644c716772b91df5,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64caefb6644c716772b92019,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64caefb9644c716772b93540,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64caefb9644c716772b93986,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64caefba644c716772b94198,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"LocalAuthorityName":{'$regex': "London"},
          "RatingValue": {"$gte": 4}}

# Use count_documents to display the number of documents in the result
print("Number of documents in result:", establishments.count_documents(query))

# Display the first document in the results using pprint

print("First result:")
results = establishments.find(query)
pprint(results[0])

Number of documents in result: 33
First result:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64caefb6644c716772b925e8'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [9]:
# Convert the result to a Pandas DataFrame
results = establishments.find(query)
London_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print("Number of rows in result: ", len(London_df))

# Display the first 10 rows of the DataFrame
London_df.head(10)

Number of rows in result:  33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64caefb6644c716772b925e8,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64caefb7644c716772b9290e,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249256,51.123623,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64caefb9644c716772b9345c,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64caefba644c716772b9425c,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346337,51.464066,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64caefba644c716772b9425d,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64caefba644c716772b94964,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64caefbc644c716772b96a77,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.069286,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64caefbc644c716772b96e3c,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.048006,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64caefbc644c716772b96e54,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64caefbc644c716772b96e55,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [10]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.4320613
longitude = 0.0740289

query = query = {
    "geocode.latitude": {"$gte": latitude - degree_search, "$lte": latitude + degree_search},
    "geocode.longitude": {"$gte": longitude - degree_search, "$lte": longitude + degree_search},
    "RatingValue": 5
    }
sort = [("scores.Hygiene", 1)]
limit = 5

# Print the results
results = list(establishments.find(query).sort(sort).limit(limit))

# Print the results
pprint(results)

[{'AddressLine1': '76 Green Lane',
  'AddressLine2': 'Chislehurst',
  'AddressLine3': '',
  'AddressLine4': '',
  'BusinessName': 'Co-op',
  'BusinessType': 'Retailers - supermarkets/hypermarkets',
  'BusinessTypeID': 7840,
  'ChangesByServerID': 0,
  'Distance': 4645.481850652601,
  'FHRSID': 358652,
  'LocalAuthorityBusinessID': '11/00111/MIXED',
  'LocalAuthorityCode': '505',
  'LocalAuthorityEmailAddress': 'food@bromley.gov.uk',
  'LocalAuthorityName': 'Bromley',
  'LocalAuthorityWebSite': 'http://www.bromley.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BR7 6AZ',
  'RatingDate': '2018-11-20T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64caefbc644c716772b95d14'),
  'geocode': {'latitude': 51.422658, 'longitude': 0.067796},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/358652',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '32 Avery Hill Road',
  'AddressLine2': '',
  'AddressLine3': 'Avery Hill',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'New Eltham Social Club',
  'BusinessType': 'Pub/bar/nightclub',
  'BusinessTypeID': 7843,
  'ChangesByServerID': 0,
  'Distance': 4645.814504371575,
  'FHRSID': 694073,
  'LocalAuthorityBusinessID': 'PI/000007353',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE9 2BD',
  'RatingDate': '2022-06-07T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64caefbc644c716772b95e45'),
  'geocode': {'latitude': 51.4386363, 'longitude': 0.0747098},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694073',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Sidcup Family Golf',
  'AddressLine2': 'Sidcup By Pass Road',
  'AddressLine3': 'Chislehurst',
  'AddressLine4': '',
  'BusinessName': 'Mr Mulligans Coffee Shop',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4645.486762099276,
  'FHRSID': 987767,
  'LocalAuthorityBusinessID': '17/00080/MIXED',
  'LocalAuthorityCode': '505',
  'LocalAuthorityEmailAddress': 'food@bromley.gov.uk',
  'LocalAuthorityName': 'Bromley',
  'LocalAuthorityWebSite': 'http://www.bromley.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BR7 6RP',
  'RatingDate': '2019-06-11T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64caefbc644c716772b95d22'),
  'geocode': {'latitude': 51.4315147399902, 'longitude': 0.0765409991145134},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/987767',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Dulverton School',
  'AddressLine2': 'Dulverton Road',
  'AddressLine3': 'London',
  'AddressLine4': '',
  'BusinessName': 'Independent Catering Management At Dulverton Primary School',
  'BusinessType': 'School/college/university',
  'BusinessTypeID': 7845,
  'ChangesByServerID': 0,
  'Distance': 4645.46991106295,
  'FHRSID': 1402880,
  'LocalAuthorityBusinessID': '21/00281/CP',
  'LocalAuthorityCode': '503',
  'LocalAuthorityEmailAddress': 'food.safety@bexley.gov.uk',
  'LocalAuthorityName': 'Bexley',
  'LocalAuthorityWebSite': 'http://www.bexley.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE9 3RH',
  'RatingDate': '2021-11-17T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64caefbc644c716772b95d09'),
  'geocode': {'latitude': 51.4354901, 'longitude': 0.0809898},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1402880',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Belmont Lane',
  'AddressLine2': 'Chislehurst',
  'AddressLine3': '',
  'AddressLine4': '',
  'BusinessName': 'Edgebury Primary School',
  'BusinessType': 'School/college/university',
  'BusinessTypeID': 7845,
  'ChangesByServerID': 0,
  'Distance': 4645.384390188426,
  'FHRSID': 357582,
  'LocalAuthorityBusinessID': '00000/0000/8/092',
  'LocalAuthorityCode': '505',
  'LocalAuthorityEmailAddress': 'food@bromley.gov.uk',
  'LocalAuthorityName': 'Bromley',
  'LocalAuthorityWebSite': 'http://www.bromley.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BR7 6BL',
  'RatingDate': '2018-10-04T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64caefbc644c716772b95ca8'),
  'geocode': {'latitude': 51.423689, 'longitude': 0.071497},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/357582',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 5}}]

In [11]:
# Convert result to Pandas DataFrame
results = establishments.find(query)
df = pd.json_normalize(results)

# Display the first 10 rows of the DataFrame
df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64caefbc644c716772b95bc2,329574,0,15290/0008/4/000,Limoncello,Restaurant/Cafe/Canteen,1,8-9 Marechal Niel Parade,Main Road,Sidcup,...,0.083451,51.430663,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64caefbc644c716772b95c0b,329565,0,15270/0327/0/000,St Mary's Nursing Home,Caring Premises,5,327 Main Road,Sidcup,Kent,...,0.082105,51.430813,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64caefbc644c716772b95c98,358390,0,07/00055/MIXED,Blossom Years Day Nursery,Caring Premises,5,Blossom Years Childrens Day Nursery,2C Imperial Way,Chislehurst,...,0.075336,51.427165,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64caefbc644c716772b95ca8,357582,0,00000/0000/8/092,Edgebury Primary School,School/college/university,7845,Belmont Lane,Chislehurst,,...,0.071497,51.423689,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64caefbc644c716772b95d09,1402880,0,21/00281/CP,Independent Catering Management At Dulverton P...,School/college/university,7845,Dulverton School,Dulverton Road,London,...,0.080990,51.435490,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64caefbc644c716772b95d14,358652,0,11/00111/MIXED,Co-op,Retailers - supermarkets/hypermarkets,7840,76 Green Lane,Chislehurst,,...,0.067796,51.422658,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64caefbc644c716772b95d22,987767,0,17/00080/MIXED,Mr Mulligans Coffee Shop,Restaurant/Cafe/Canteen,1,Sidcup Family Golf,Sidcup By Pass Road,Chislehurst,...,0.076541,51.431515,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64caefbc644c716772b95d87,1451407,0,14959,Oaks Nursing Home,Caring Premises,5,The Oaks 904 Sidcup Road,,Eltham,...,0.074029,51.432061,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64caefbc644c716772b95e34,694530,0,PI/000104365,Providence Linc United Services,Caring Premises,5,88 Montbelle Road,,Eltham,...,0.066657,51.430024,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64caefbc644c716772b95e45,694073,0,PI/000007353,New Eltham Social Club,Pub/bar/nightclub,7843,32 Avery Hill Road,,Avery Hill,...,0.074710,51.438636,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [12]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': {"LocalAuthorityName": "$LocalAuthorityName"}, 
                          'count': { '$sum': 1 }
                         }
              }
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1 }}
limit = 5
# Print the number of documents in the result
pipeline = [match_query, group_query, sort_values]
# Print the first 10 results
results = list(establishments.aggregate(pipeline))
pprint(results[0:10])

[{'_id': {'LocalAuthorityName': 'Thanet'}, 'count': 1130},
 {'_id': {'LocalAuthorityName': 'Greenwich'}, 'count': 882},
 {'_id': {'LocalAuthorityName': 'Maidstone'}, 'count': 713},
 {'_id': {'LocalAuthorityName': 'Newham'}, 'count': 711},
 {'_id': {'LocalAuthorityName': 'Swale'}, 'count': 686},
 {'_id': {'LocalAuthorityName': 'Chelmsford'}, 'count': 680},
 {'_id': {'LocalAuthorityName': 'Medway'}, 'count': 672},
 {'_id': {'LocalAuthorityName': 'Bexley'}, 'count': 607},
 {'_id': {'LocalAuthorityName': 'Southend-On-Sea'}, 'count': 586},
 {'_id': {'LocalAuthorityName': 'Tendring'}, 'count': 542}]

In [13]:
# Convert the result to a Pandas DataFrame
result_df = pd.json_normalize(results)

df = result_df.rename(columns={"_id.LocalAuthorityName": "Local Authority Name", "count": "Count"})
df = df[["Local Authority Name", "Count"]]
# Print out the length of the DataFrame
print("Rows in DataFrame: ", len(result_df))

# Display the first 10 rows of the DataFrame
df.head(10)

Rows in DataFrame:  55

  Local Authority Name  Count
0               Thanet   1130
1            Greenwich    882
2            Maidstone    713
3               Newham    711
4                Swale    686
5           Chelmsford    680
6               Medway    672
7               Bexley    607
8      Southend-On-Sea    586
9             Tendring    542